function savevrml(node,elem,face,fname)
%
% savevrml(node,elem,face,fname)
%
% save a surface mesh to VRML 1.0 format
%
% author: Qianqian Fang (fangq<at> nmr.mgh.harvard.edu)
% date: 2010/04/25
%
% input:
%      node: input, surface node list, dimension (nn,3)
%      elem: input, tetrahedral element list, dimension (ne,4)
%      face: input, surface face element list, dimension (be,3)
%      fname: output file name
%
% -- this function is part of iso2mesh toolbox (http://iso2mesh.sf.net)
%

fid=fopen(fname,'wt');
if(fid==-1)
    error(['You do not have permission to save mesh files, if you are working in a multi-user ',...
         'environment, such as Unix/Linux and there are other users using iso2mesh, ',...
         'you may need to define ISO2MESH_SESSION=''yourstring'' to make your output ',...
         'files different from others; if you do not have permission to ',mwpath(''),...
         ' as the temporary directory, you have to define ISO2MESH_TEMP=''/folder/you/have/write/permission'' ',...
         'in matlab/octave base workspace.']);
end

fprintf(fid,'#VRML V1.0 ascii\n#Generated by iso2mesh (http://iso2mesh.sf.net)\n');
fprintf(fid,'Separator {\nSwitch {\n\tDEF %s\n\tSeparator {\n',fname);

if(~isempty(node))
  fprintf(fid,'\t\tCoordinate3 {\n\t\t\tpoint [\n');
  fprintf(fid,'%f %f %f,\n',node');
  fprintf(fid,'\t\t\t]\n\t\t}\n');
end

if(~isempty(face))
  fprintf(fid,'\t\tIndexedFaceSet {\n\t\t\tcoordIndex [\n');
  fprintf(fid,'%d %d %d -1\n',(face-1)');
  fprintf(fid,'\t\t\t]\n\t\t}\n');
end

fprintf(fid,'\t} # Separator\n}\n}\n');

fclose(fid);
